---
- name: Configure Windows hosts
  hosts: all
  vars:
    my_service: BITS
  tasks:
  - name: Install IIS (Web-Server and Web-Common-Http)
    win_feature:
      name:
      - Web-Server
      - Web-Common-Http
      include_sub_features: true
      state: present

  - name: Uninstall DHCP
    win_feature:
      name:
      - DHCP
      state: absent

  - name: Set service startup mode to auto and ensure it is started
    win_service:
      name: "{{ my_service }}"
      start_mode: auto
      state: started