---
- name: Configure Windows hosts
  hosts: all
  vars:
    my_service: BITS
    config_path: C:\Temp\config
  tasks:
  - name: Install IIS (Web-Server and Web-Common-Http)
    win_feature:
      name:
      - Web-Server
      - Web-Common-Http
      include_sub_features: true
      state: present

  - name: Uninstall DHCP
    win_feature:
      name:
      - DHCP
      state: absent

  - name: Set service startup mode to auto and ensure it is started
    win_service:
      name: "{{ my_service }}"
      start_mode: auto
      state: started

  - name: Create directory structure
    win_file:
      path: "{{ config_path }}"
      state: directory

  - name: copy config file
    win_copy:
      src: config.txt
      dest: "{{ config_path }}\\importantconfig.txt" 