---
- name: Configure Windows hosts
  hosts: all
  vars:
    my_service: BITS
    config_path: C:\Temp\config
    reg_keys:
    - NoAutoRebootWithLoggedOnUsers
    - NoAutoUpdate
  tasks:
  - name: Install IIS (Web-Server and Web-Common-Http)
    win_feature:
      name:
      - Web-Server
      - Web-Common-Http
      include_sub_features: true
      state: present

  - name: Uninstall DHCP
    win_feature:
      name:
      - DHCP
      state: absent

  - name: Set service startup mode to auto and ensure it is started
    win_service:
      name: "{{ my_service }}"
      start_mode: auto
      state: started

  - name: Create directory structure
    win_file:
      path: "{{ config_path }}"
      state: directory

  - name: copy config file
    win_copy:
      src: config.txt
      dest: "{{ config_path }}\\importantconfig.txt" 


  - name: Add or update registry values
    win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
      name: "{{ item }}"
      data: 00000001
      type: dword
    loop: "{{ reg_keys }}"

  - name: Install the Visual C thingy
    win_package:
      path: https://github.com/petrkle/vim-msi/releases/download/v8.1.55/vim-8.1.55.msi
      product_id: '{CF2BEA3C-26EA-32F8-AA9B-331F7E34BA97}'
      arguments: /passive


